# -*- coding: utf-8 -*-
"""assg3q5.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1KrMW6pKeynCTJPrvzJSyr3KmYIin_8gn
"""

list_of_marks=(12,18,25,24,2,5,18,20,20,21)

def find_more_than_average():
    count = 0
    avg = sum(list_of_marks)/len(list_of_marks)

    for i in list_of_marks:
        if i > avg:
            count += 1
    percentage = (count / len(list_of_marks)) * 100
    return percentage

def generate_frequency():
    freq_list = []
    student_count = 0
    for i in range(0, 26):
        for j in list_of_marks:
         
            if j == i:
                student_count += 1
        freq_list.append(student_count)
        student_count = 0
                
    
    return freq_list
            

def sort_marks():
    
    sorted_list = sorted(list_of_marks)
    return sorted_list

print(find_more_than_average())
print(generate_frequency())
print(sort_marks())
