# -*- coding: utf-8 -*-
"""assg3q3.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1JBBARmKcEuJa1sZv1q8qkRL9Hx08X-dE
"""

def check_double(number):
    num=str(number)
    doub=number*2
    dou=str(doub)
    count=0
    
    for i in num:
        if i in dou:
            count+=1
            
        else:
            return False
            break
    
    if len(num)==count :
        return True

print(check_double(125874))